config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root :to => 'profile#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end

    post 'sync', to: "sync#sync", as: :sync
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :location
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def set_location sync_params
    location = self.location || Location.new
    location.user = self
    location.lonlat = "POINT(#{sync_params['lon'].to_f} #{sync_params['lat'].to_f})"
    location.save

    location
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def new

  end

  def index

  end

end

app/controllers/sync_controller.rb
class SyncController < ApplicationController
  def sync
    location = current_user.set_location sync_params if user_signed_in?
    lat = sync_params[:lat]
    lon = sync_params[:lon]

    locs = Location.where "ST_DWithin(lonlat, 'POINT(? ?)', 500.0)", lon.to_f, lat.to_f
    locs = locs.where "updated_at >= now() - INTERVAL '3 minutes'"
    locs = locs.where "user_id <> ?", current_user.id
    logger.debug " LOCS: #{locs.to_a.inspect}"
    points = locs.map{|x| [x.lonlat.x, x.lonlat.y]}
    render js: "showPins(#{points})"
  end

def refresh_points

end

  private

  def sync_params
    params.require(:sync).permit :lat, :lon
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Huggles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared/navbar" %>

<%= yield %>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=false&callback=initialize" ></script>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Huggles</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to  "Home", authenticated_root_path %></li>
        <li class="active">
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
            </li>
        <% else %>
            <li>
              <%= link_to 'Login', new_user_session_path  %>
            </li>
        <% end %>
        <li class="active">
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Edit User', edit_user_registration_path %>
            </li>
        <% else %>
            <li>
              <%= link_to 'Sign Up', new_user_registration_path %>
            </li>
        <% end %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>